version: "3"

tasks:
  clean:
    cmds:
      - rm -rf build

  format:
    cmds:
      - deno fmt ./

  build:
    cmds:
      - builder --source-path ./src --build-path build/site/ --base-url https://patrickcrocker.com
    deps:
      - format

  serve:
    cmds:
      - builder --source-path ./src --build-path build/site/ --base-url https://patrickcrocker.com --serve
    deps:
      - format
